/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Motor1 */
#define Motor1_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Motor1_0_INBUF_ENABLED 0u
#define Motor1_0_INIT_DRIVESTATE 1u
#define Motor1_0_INIT_MUXSEL 8u
#define Motor1_0_INPUT_SYNC 2u
#define Motor1_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Motor1_0_NUM 6u
#define Motor1_0_PORT GPIO_PRT12
#define Motor1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Motor1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Motor1_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Motor1_INBUF_ENABLED 0u
#define Motor1_INIT_DRIVESTATE 1u
#define Motor1_INIT_MUXSEL 8u
#define Motor1_INPUT_SYNC 2u
#define Motor1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Motor1_NUM 6u
#define Motor1_PORT GPIO_PRT12
#define Motor1_SLEWRATE CY_GPIO_SLEW_FAST
#define Motor1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Motor2 */
#define Motor2_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Motor2_0_INBUF_ENABLED 0u
#define Motor2_0_INIT_DRIVESTATE 1u
#define Motor2_0_INIT_MUXSEL 8u
#define Motor2_0_INPUT_SYNC 2u
#define Motor2_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Motor2_0_NUM 6u
#define Motor2_0_PORT GPIO_PRT10
#define Motor2_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Motor2_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Motor2_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Motor2_INBUF_ENABLED 0u
#define Motor2_INIT_DRIVESTATE 1u
#define Motor2_INIT_MUXSEL 8u
#define Motor2_INPUT_SYNC 2u
#define Motor2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Motor2_NUM 6u
#define Motor2_PORT GPIO_PRT10
#define Motor2_SLEWRATE CY_GPIO_SLEW_FAST
#define Motor2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_1_rx */
#define UART_1_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_1_rx_0_INBUF_ENABLED 1u
#define UART_1_rx_0_INIT_DRIVESTATE 1u
#define UART_1_rx_0_INIT_MUXSEL 18u
#define UART_1_rx_0_INPUT_SYNC 2u
#define UART_1_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_rx_0_NUM 4u
#define UART_1_rx_0_PORT GPIO_PRT6
#define UART_1_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_1_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_1_rx_INBUF_ENABLED 1u
#define UART_1_rx_INIT_DRIVESTATE 1u
#define UART_1_rx_INIT_MUXSEL 18u
#define UART_1_rx_INPUT_SYNC 2u
#define UART_1_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_rx_NUM 4u
#define UART_1_rx_PORT GPIO_PRT6
#define UART_1_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_1_tx */
#define UART_1_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_1_tx_0_INBUF_ENABLED 0u
#define UART_1_tx_0_INIT_DRIVESTATE 1u
#define UART_1_tx_0_INIT_MUXSEL 18u
#define UART_1_tx_0_INPUT_SYNC 2u
#define UART_1_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_tx_0_NUM 5u
#define UART_1_tx_0_PORT GPIO_PRT6
#define UART_1_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_1_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_1_tx_INBUF_ENABLED 0u
#define UART_1_tx_INIT_DRIVESTATE 1u
#define UART_1_tx_INIT_MUXSEL 18u
#define UART_1_tx_INPUT_SYNC 2u
#define UART_1_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_tx_NUM 5u
#define UART_1_tx_PORT GPIO_PRT6
#define UART_1_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* SPI_1_ss_s */
#define SPI_1_ss_s_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define SPI_1_ss_s_0_INBUF_ENABLED 1u
#define SPI_1_ss_s_0_INIT_DRIVESTATE 1u
#define SPI_1_ss_s_0_INIT_MUXSEL 20u
#define SPI_1_ss_s_0_INPUT_SYNC 2u
#define SPI_1_ss_s_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SPI_1_ss_s_0_NUM 3u
#define SPI_1_ss_s_0_PORT GPIO_PRT5
#define SPI_1_ss_s_0_SLEWRATE CY_GPIO_SLEW_FAST
#define SPI_1_ss_s_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define SPI_1_ss_s_DRIVEMODE CY_GPIO_DM_HIGHZ
#define SPI_1_ss_s_INBUF_ENABLED 1u
#define SPI_1_ss_s_INIT_DRIVESTATE 1u
#define SPI_1_ss_s_INIT_MUXSEL 20u
#define SPI_1_ss_s_INPUT_SYNC 2u
#define SPI_1_ss_s_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SPI_1_ss_s_NUM 3u
#define SPI_1_ss_s_PORT GPIO_PRT5
#define SPI_1_ss_s_SLEWRATE CY_GPIO_SLEW_FAST
#define SPI_1_ss_s_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* SPI_1_miso_s */
#define SPI_1_miso_s_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define SPI_1_miso_s_0_INBUF_ENABLED 0u
#define SPI_1_miso_s_0_INIT_DRIVESTATE 1u
#define SPI_1_miso_s_0_INIT_MUXSEL 20u
#define SPI_1_miso_s_0_INPUT_SYNC 2u
#define SPI_1_miso_s_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SPI_1_miso_s_0_NUM 1u
#define SPI_1_miso_s_0_PORT GPIO_PRT5
#define SPI_1_miso_s_0_SLEWRATE CY_GPIO_SLEW_FAST
#define SPI_1_miso_s_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define SPI_1_miso_s_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define SPI_1_miso_s_INBUF_ENABLED 0u
#define SPI_1_miso_s_INIT_DRIVESTATE 1u
#define SPI_1_miso_s_INIT_MUXSEL 20u
#define SPI_1_miso_s_INPUT_SYNC 2u
#define SPI_1_miso_s_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SPI_1_miso_s_NUM 1u
#define SPI_1_miso_s_PORT GPIO_PRT5
#define SPI_1_miso_s_SLEWRATE CY_GPIO_SLEW_FAST
#define SPI_1_miso_s_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* SPI_1_mosi_s */
#define SPI_1_mosi_s_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define SPI_1_mosi_s_0_INBUF_ENABLED 1u
#define SPI_1_mosi_s_0_INIT_DRIVESTATE 1u
#define SPI_1_mosi_s_0_INIT_MUXSEL 20u
#define SPI_1_mosi_s_0_INPUT_SYNC 2u
#define SPI_1_mosi_s_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SPI_1_mosi_s_0_NUM 0u
#define SPI_1_mosi_s_0_PORT GPIO_PRT5
#define SPI_1_mosi_s_0_SLEWRATE CY_GPIO_SLEW_FAST
#define SPI_1_mosi_s_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define SPI_1_mosi_s_DRIVEMODE CY_GPIO_DM_HIGHZ
#define SPI_1_mosi_s_INBUF_ENABLED 1u
#define SPI_1_mosi_s_INIT_DRIVESTATE 1u
#define SPI_1_mosi_s_INIT_MUXSEL 20u
#define SPI_1_mosi_s_INPUT_SYNC 2u
#define SPI_1_mosi_s_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SPI_1_mosi_s_NUM 0u
#define SPI_1_mosi_s_PORT GPIO_PRT5
#define SPI_1_mosi_s_SLEWRATE CY_GPIO_SLEW_FAST
#define SPI_1_mosi_s_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* SPI_1_sclk_s */
#define SPI_1_sclk_s_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define SPI_1_sclk_s_0_INBUF_ENABLED 1u
#define SPI_1_sclk_s_0_INIT_DRIVESTATE 1u
#define SPI_1_sclk_s_0_INIT_MUXSEL 20u
#define SPI_1_sclk_s_0_INPUT_SYNC 2u
#define SPI_1_sclk_s_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SPI_1_sclk_s_0_NUM 2u
#define SPI_1_sclk_s_0_PORT GPIO_PRT5
#define SPI_1_sclk_s_0_SLEWRATE CY_GPIO_SLEW_FAST
#define SPI_1_sclk_s_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define SPI_1_sclk_s_DRIVEMODE CY_GPIO_DM_HIGHZ
#define SPI_1_sclk_s_INBUF_ENABLED 1u
#define SPI_1_sclk_s_INIT_DRIVESTATE 1u
#define SPI_1_sclk_s_INIT_MUXSEL 20u
#define SPI_1_sclk_s_INPUT_SYNC 2u
#define SPI_1_sclk_s_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SPI_1_sclk_s_NUM 2u
#define SPI_1_sclk_s_PORT GPIO_PRT5
#define SPI_1_sclk_s_SLEWRATE CY_GPIO_SLEW_FAST
#define SPI_1_sclk_s_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
