/*******************************************************************************
* File Name: cyfitter_sysint_cfg.c
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_sysint.h"
#include "cyfitter_sysint_cfg.h"

/* ARM CM4 */
#if (((__CORTEX_M == 4) && (CY_CORE_ID == 0)))

    /* SPI_1_SCB_IRQ */
    const cy_stc_sysint_t SPI_1_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)SPI_1_SCB_IRQ__INTC_NUMBER,
        .intrPriority = SPI_1_SCB_IRQ__INTC_CORTEXM4_PRIORITY
    };

    /* UART_1_SCB_IRQ */
    const cy_stc_sysint_t UART_1_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)UART_1_SCB_IRQ__INTC_NUMBER,
        .intrPriority = UART_1_SCB_IRQ__INTC_CORTEXM4_PRIORITY
    };

    /* SysInt_1 */
    const cy_stc_sysint_t SysInt_1_cfg = {
        .intrSrc = (IRQn_Type)SysInt_1__INTC_NUMBER,
        .intrPriority = SysInt_1__INTC_CORTEXM4_PRIORITY
    };

    /* SysInt_10 */
    const cy_stc_sysint_t SysInt_10_cfg = {
        .intrSrc = (IRQn_Type)SysInt_10__INTC_NUMBER,
        .intrPriority = SysInt_10__INTC_CORTEXM4_PRIORITY
    };

    /* SysInt_11 */
    const cy_stc_sysint_t SysInt_11_cfg = {
        .intrSrc = (IRQn_Type)SysInt_11__INTC_NUMBER,
        .intrPriority = SysInt_11__INTC_CORTEXM4_PRIORITY
    };

    /* SysInt_2 */
    const cy_stc_sysint_t SysInt_2_cfg = {
        .intrSrc = (IRQn_Type)SysInt_2__INTC_NUMBER,
        .intrPriority = SysInt_2__INTC_CORTEXM4_PRIORITY
    };

    /* SysInt_3 */
    const cy_stc_sysint_t SysInt_3_cfg = {
        .intrSrc = (IRQn_Type)SysInt_3__INTC_NUMBER,
        .intrPriority = SysInt_3__INTC_CORTEXM4_PRIORITY
    };

    /* SysInt_4 */
    const cy_stc_sysint_t SysInt_4_cfg = {
        .intrSrc = (IRQn_Type)SysInt_4__INTC_NUMBER,
        .intrPriority = SysInt_4__INTC_CORTEXM4_PRIORITY
    };

    /* SysInt_5 */
    const cy_stc_sysint_t SysInt_5_cfg = {
        .intrSrc = (IRQn_Type)SysInt_5__INTC_NUMBER,
        .intrPriority = SysInt_5__INTC_CORTEXM4_PRIORITY
    };

    /* SysInt_6 */
    const cy_stc_sysint_t SysInt_6_cfg = {
        .intrSrc = (IRQn_Type)SysInt_6__INTC_NUMBER,
        .intrPriority = SysInt_6__INTC_CORTEXM4_PRIORITY
    };

    /* SysInt_7 */
    const cy_stc_sysint_t SysInt_7_cfg = {
        .intrSrc = (IRQn_Type)SysInt_7__INTC_NUMBER,
        .intrPriority = SysInt_7__INTC_CORTEXM4_PRIORITY
    };

    /* SysInt_8 */
    const cy_stc_sysint_t SysInt_8_cfg = {
        .intrSrc = (IRQn_Type)SysInt_8__INTC_NUMBER,
        .intrPriority = SysInt_8__INTC_CORTEXM4_PRIORITY
    };

    /* SysInt_9 */
    const cy_stc_sysint_t SysInt_9_cfg = {
        .intrSrc = (IRQn_Type)SysInt_9__INTC_NUMBER,
        .intrPriority = SysInt_9__INTC_CORTEXM4_PRIORITY
    };

    /* int_EmergencyStop */
    const cy_stc_sysint_t int_EmergencyStop_cfg = {
        .intrSrc = (IRQn_Type)int_EmergencyStop__INTC_NUMBER,
        .intrPriority = int_EmergencyStop__INTC_CORTEXM4_PRIORITY
    };

#endif /* ((__CORTEX_M == 4) && (CY_CORE_ID == 0)) */

