/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* SysInt_1 */
#define SysInt_1__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_1__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_1__INTC_NUMBER 122u
#define SysInt_1_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_1_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_1_INTC_NUMBER 122u

/* SysInt_2 */
#define SysInt_2__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_2__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_2__INTC_NUMBER 125u
#define SysInt_2_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_2_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_2_INTC_NUMBER 125u

/* SysInt_3 */
#define SysInt_3__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_3__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_3__INTC_NUMBER 126u
#define SysInt_3_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_3_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_3_INTC_NUMBER 126u

/* SysInt_4 */
#define SysInt_4__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_4__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_4__INTC_NUMBER 127u
#define SysInt_4_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_4_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_4_INTC_NUMBER 127u

/* SysInt_5 */
#define SysInt_5__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_5__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_5__INTC_NUMBER 128u
#define SysInt_5_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_5_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_5_INTC_NUMBER 128u

/* SysInt_6 */
#define SysInt_6__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_6__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_6__INTC_NUMBER 129u
#define SysInt_6_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_6_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_6_INTC_NUMBER 129u

/* SysInt_7 */
#define SysInt_7__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_7__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_7__INTC_NUMBER 130u
#define SysInt_7_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_7_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_7_INTC_NUMBER 130u

/* SysInt_8 */
#define SysInt_8__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_8__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_8__INTC_NUMBER 131u
#define SysInt_8_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_8_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_8_INTC_NUMBER 131u

/* SysInt_9 */
#define SysInt_9__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_9__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_9__INTC_NUMBER 132u
#define SysInt_9_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_9_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_9_INTC_NUMBER 132u

/* SysInt_10 */
#define SysInt_10__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_10__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_10__INTC_NUMBER 123u
#define SysInt_10_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_10_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_10_INTC_NUMBER 123u

/* SysInt_11 */
#define SysInt_11__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_11__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_11__INTC_NUMBER 124u
#define SysInt_11_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_11_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_11_INTC_NUMBER 124u

/* SPI_1_SCB_IRQ */
#define SPI_1_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define SPI_1_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define SPI_1_SCB_IRQ__INTC_NUMBER 42u
#define SPI_1_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define SPI_1_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define SPI_1_SCB_IRQ_INTC_NUMBER 42u

/* UART_1_SCB_IRQ */
#define UART_1_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define UART_1_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define UART_1_SCB_IRQ__INTC_NUMBER 46u
#define UART_1_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define UART_1_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define UART_1_SCB_IRQ_INTC_NUMBER 46u

/* int_EmergencyStop */
#define int_EmergencyStop__INTC_CORTEXM4_ASSIGNED 1
#define int_EmergencyStop__INTC_CORTEXM4_PRIORITY 7u
#define int_EmergencyStop__INTC_NUMBER 133u
#define int_EmergencyStop_INTC_CORTEXM4_ASSIGNED 1
#define int_EmergencyStop_INTC_CORTEXM4_PRIORITY 7u
#define int_EmergencyStop_INTC_NUMBER 133u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
