@REM This script allows a 3rd party IDE to use cymcuelftool.exe to perform
@REM the post processing that is necessary to update the *.elf file
@REM generated by the linker into a complete memory image to use in
@REM programming the PSoC.
@REM NOTE: This script is auto generated. Do not modify.
IF /I "%~5" NEQ "iar" GOTO not_iar
chdir /d "%~2\Export"
@IF %errorlevel% NEQ 0 EXIT /b %errorlevel%
move /Y "%~1" "%~3\%~n1_link.out"
@IF %errorlevel% NEQ 0 EXIT /b %errorlevel%
@setlocal enabledelayedexpansion
@set CurrentLinkFile="%~3\%~n1_link.out"
@set SignedLinkFile="%~3\%~n1_signed.out"
@set MergeFiles=%SignedLinkFile%

@REM If you have changed the CortexM0p-based project executable output directory, then please provide your location here:
@set CORTEXM0P_OUTPUT_DIRECTORY=%~2\%~6\Exe

for %%i in ("%CORTEXM0P_OUTPUT_DIRECTORY%\*_link.out") do @(
IF "%%i" NEQ "%~3\%~n1_link.out" set MergeFiles=!MergeFiles! "%%i"
)
set MergeFiles=%MergeFiles:_link=%
"%~2\Export\cymcuelftool.exe" --sign %CurrentLinkFile% --output %SignedLinkFile%
@IF %errorlevel% NEQ 0 EXIT /b %errorlevel%
"%~2\Export\cymcuelftool.exe" --merge %MergeFiles% --output "%~1"
@IF %errorlevel% NEQ 0 EXIT /b %errorlevel%
EXIT

:not_iar
